import { SoundProvider } from "@/helpers/context/SoundContext";
import "./globals.css";
import localFont from "next/font/local";
import { useState } from "react";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<SoundProvider>{children}</SoundProvider>
			</body>
		</html>
	);
}
